<a href="https://colab.research.google.com/github/kara04y/2026_Intro_Python/blob/main/Python_formula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PYTHON FORMULA**

---



# Cours 1: Variables
1) int : integer, whole numerical count (int()) truncates it doest not round int(2.99)=2
2) float: floating point, real-valued measurements
3) str: string, textual data
4) bool: boolean, true/false
nonetype : None

Rules for variable:
1) first character = letter or _
2) NO whitespace . - @ $ % !
3) diff between t and T
4)NO python kyeword (for, if, class, return, print, id, open, min, max)

Comparison operators return bool
print(temp_kelvin > 270.0)




In [ ]:
# Assignment operators update a variable in place
count = 0
count += 3          # same as count = count + 3
count -= 1
count *= 2
print(count)        # 4

#Comparison operators return bool
print(temp_kelvin > 270.0)        # True
print(is_freezing and is_valid)   # True: both conditions hold
print(is_freezing or False)       # True: at least one holds


4


NameError: name 'temp_kelvin' is not defined

In [ ]:
#Converting
pressure_pa = float(raw)
print(raw, type(raw))                     # 614.0 <class 'str'>
round(1.6676, 2)                          # round to two decimal 1.67
print(f"pressure = {pressure_pa:.2f} Pa") # .2f = two decimals

In [ ]:
#Slicing
print(station_name[0], station_name[-1])  # print the first letter end the last
print(station_name[0:5])                  # Jungf
print(station_name[:5])                   # start defaults from 0

#String Methods
record = "JUNGFRAUJOCH,-9.2,degC"
fields = record.split(",")        # vector splitted where , is ['JUNGFRAUJOCH','-9.2','degC']
fields = record.strip(",")        # removes whitespaces
name_lowercase = name.lower()     # or .upper or .title

In [ ]:
# Librairies / Files / Path
import math

from pathlib import Path

data_path = Path("_files/station_daily.csv")
data_path.parent.mkdir(exist_ok=True)         # create the folder if needed

# "w" creates the file (or overwrites it); the with block closes it automatically
with data_path.open("w", encoding="utf-8") as fhandler:
    fhandler.write("station,day,max_temp_celsius\n")
print(f"Does the file exist now? {data_path.exists()}")

# "a" réopens the same file and adds to the end
with data_path.open("a", encoding="utf-8") as fhandler:
    fhandler.write("JFJ,2022-01-02,-8.9\n")
    fhandler.write("JFJ,2022-01-03,-9.2\n")

# "r" reads it back; .read() returns the whole file as one string
with data_path.open("r", encoding="utf-8") as fhandler:
    raw_text = fhandler.read()

# .readlines() gives a list of lines instead of one long string
with data_path.open("r", encoding="utf-8") as fhandler:
    all_lines = fhandler.readlines()

# Cours 2 : Data structures and control flow

In [ ]:
# a list: ordered, mutable sequence of daily mean temperatures (°C)
readings_celsius = [-2.3, -1.1, 0.4, 1.2, -0.8]
readings_celsius.append(-3.1)          # add to the end
readings_celsius.insert(0, -1.9)       # add at a specific position
readings_celsius.remove(0.4)           # remove a specific value
print(readings_celsius)

# indexing and slicing: access individual items or a range of items
print(readings_celsius[0], readings_celsius[-1])        # -2.3 and -0.8
print(readings_celsius[1:3])                            # a slice: items at index 1 and 2

print(len(readings_celsius))           # get the length of a list


In [ ]:
# a tuple: immutable record, here a (lat, lon) coordinate in degrees
station_coords = (46.5475, 7.9853)
lat, lon = station_coords              # unpacking into two names
print(lat, lon)

In [ ]:
# Dictionary : unique, immutable keys to values
station = {
    "name": "Jungfraujoch",
    "elevation_m": 3571,
    "coordinates": (46.5475, 7.9853),
    "readings_celsius": [-2.3, -1.1, 0.4, 1.2, -0.8],
    }

stations = {
    "JFJ": {"name": "Jungfraujoch", "elevation_m": 3571, "readings_celsius": [-2.3, -1.1]},
    "BAS": {"name": "Basel-Binningen", "elevation_m": 316, "readings_celsius": [6.1, 7.4]}
}

print(station["name"])                # look up an element
station["country"] = "Switzerland"    # add an element
print(station.items())                # .items() yields the key-value pairs

In [ ]:
# Control flow
temp_celsius = 6.1
if temp_celsius < 0.0:
    category = "freezing"
elif temp_celsius < 10.0:
    category = "cold"
elif temp_celsius < 20.0:
    category = "mild"
else:
    category = "warm"
print(category)

In [ ]:
# loops
basel_readings_celsius = [6.1, 7.4, 5.9, 8.2, 6.8]
for temp in basel_readings_celsius:   #temp can be whatever
    print(temp)

# Loop over indices in a list: enumerate gives index + value
for i, temp in enumerate(basel_readings_celsius):
    print(i, temp)

# zip pairs two sequences
for date, temp in zip(dates, basel_readings_celsius):
    print(date, temp)

# While loops
day = 0
while day < len(basel_readings_celsius):        # loop until the index reaches the length
    if basel_readings_celsius[day] > 7.0:
        print("warm day:", dates[day], basel_readings_celsius[day])
    day += 1

# Break
hot_temp = None                     # define it first, in case no hot day is found
day = 0
while day < len(basel_readings_celsius):
    temp = basel_readings_celsius[day]
    if temp > 8.0:
        print("Found a hot day, stopping!")
        hot_temp = temp
        break
    print("Processing:", temp)
    day += 1

print("Hot day temperature:", hot_temp)

# continue
mixed = [6.1, None, 5.9, None, 6.8]
total, n = 0.0, 0
for value in mixed:
    if value is None:
        print("Found None value in list.")
        continue # skip missing values represented as None
    total += value
    n += 1
print("Mean of present values:", round(total / n, 2))


In [ ]:
# Functions
def compute_sum(values):
    total = 0.0
    for v in values:
        total += v
    return total
print(compute_sum([1.0, 2.0, 3.0]))      # 6.0

def mean_of(*values):
    total = 0.0
    for v in values:
        total += v
    return total / len(values)

print(round(mean_of(6.1, 7.4, 5.9), 2))  # 6.47

6.0
6.47


# Cours 3 : Numpy
Used instead of list and loopes. An ndarray differs in three ways
1) the dimensions of a list is 1D where ndarray can be any number
2) the content can be anything fro a list where ndarray content is one dtype for every element (ex onyl float)


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])

temp_celsius = np.array([                 # a 2D field: 3(rows) x 6(cols)
    [ 5.2,  4.8,  6.1,  3.9,  2.7,  4.4],
    [ 1.3,  0.5, -0.8, -1.2,  0.9,  2.1],
    [-2.6, -3.1, -1.9,  0.2, -0.5,  1.1],
])

print(temp_celsius[0, 0])      # one element
print(temp_celsius[0, :])      # first row, all longitudes
print(temp_celsius[:, -1])     # last column, all latitudes
print(temp_celsius[1:3, 2:4])  # a 2x2 sub-block

# a boolean mask and what it selects
freezing = temp_celsius < 0.0
print("n freezing cells:", int(freezing.sum()))    # True counts as 1
print("freezing values:", temp_celsius[freezing])  # 1D of matches

Broadcasting : Broadcasting lets arrays of different but compatible shapes combine. Broadcasting aligns shapes from the last axis backwards.
```
# (4,1) + (4,6) -> (4,6)
```

In [ ]:
#Broadcasting : Broadcasting lets arrays of different but compatible shapes combine.
# Broadcasting aligns shapes from the last axis backwards.  (4,1) + (4,6) -> (4,6)

In [ ]:
print(lat_gradient_celsius.shape)                  # (4,)   — a flat vector
print(lat_gradient_celsius[:, None].shape)         # (4, 1) — now a column

In [ ]:
# mean
print(temp_celsius.mean(), np.mean(temp_celsius))
# sum
print(temp_celsius.sum(), np.sum(temp_celsius))  # 11.0 — only the final total
print(daily_rain_mm.cumsum())                    # [ 0.   2.5  2.5  9.5 11. ] — rain to date


print("overall mean:", temp_celsius.mean())
print("mean per column (over rows):", temp_celsius.mean(axis=0))
print("mean per row (over columns):", temp_celsius.mean(axis=1))
print("min, max:", temp_celsius.min(), temp_celsius.max())
print("argmin, argmax (index of tge smallest/largest value):", temp_celsius.argmin(), temp_celsius.argmax())

#reshape
flat = temp_celsius.reshape(-1)
print("reshaped:", flat.shape)

# stacking: combine arrays along a new row axis
col_means = temp_celsius.mean(axis=0)  # find the mean of each collum
index_row = np.arange(6, dtype=float)
print("vstacked:", np.vstack([index_row, col_means]).shape)

# np.where(condition, a, b): element-wise choice
category = np.where(temp_celsius < 0.0, "freezing", "above")
print(category)

# np.interp: fill a 1D gap by linear interpolation against an index
profile = temp_celsius[:, 0].copy()      # the first column, 4 latitudes
x = np.arange(profile.size)
known = np.array([0, 1, 3])              # pretend index 2 is missing
filled = np.interp(x, known, profile[known])
print(profile)
print(filled)


(3, 4)
(1, 4)
[[10.4  9.6 12.2  8.8]
 [ 6.5  5.3  5.3  6.5]
 [ 2.6  1.7  4.2  5.5]]
[[10.4  9.6 12.2  8.8]
 [ 6.5  5.3  5.3  6.5]
 [ 2.6  1.7  4.2  5.5]]


# Cours 4 : Visualisation with Matplotlib

In [ ]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])
plt.show()

# Subplot for one graph
fig = plt.figure()
axes = fig.subplots(nrows=2, ncols=3)
plt.show()
# OR
fig, ax = plt.subplots()
ax.plot(days, ts_celsius)
plt.show()

#Subplot for multiple graphs
fig, axes = plt.subplots(figsize=(8, 4), ncols=2)
ax0, ax1 = axes
ax0.plot(days, ts_celsius)
ax1.plot(days, rh_percent)
plt.show()

#Full code for a complete graph
fig, axes = plt.subplots(figsize=(8, 4), ncols=2)
ax0, ax1 = axes

ax0.plot(days, ts_celsius)
ax0.set_xlabel("day of year")
ax0.set_ylabel("temperature (°C)")
ax0.set_title("daily mean air temperature")

ax1.plot(days, rh_percent)
ax1.set_xlabel("day of year")
ax1.set_ylabel("relative humidity (%)")
ax1.set_title("daily mean relative humidity")

# squeeze everything in
plt.tight_layout()
plt.show()

In [ ]:
# Line styles
fig, axes = plt.subplots(figsize=(14, 4), ncols=3)

axes[0].plot(days, ts_celsius, linestyle="dashed")
axes[0].plot(days, ridge_celsius, linestyle="--")

axes[1].plot(days, ts_celsius, linestyle="dotted")
axes[1].plot(days, ridge_celsius, linestyle=":")

axes[2].plot(days, ts_celsius, linestyle="dashdot", linewidth=5)
axes[2].plot(days, ridge_celsius, linestyle="-.", linewidth=0.5)

for ax in axes:
    ax.set_xlabel("day of year")
    ax.set_ylabel("temperature (°C)")
plt.tight_layout()
plt.show()

# Colours : b=blue, g=green, r=red, c=cyan, m=magenta, y=yellow, k=black, w=white
ax.plot(days, ts_celsius, color="k")
axes[0].plot(days, ts_celsius, color="0.8") #grey scale

# Legend
ax.legend(ncols=2, fontsize=8, title="station elevation")

# Markers
axes[0].plot(days[:20], ts_celsius[:20], marker=".")
axes[0].plot(days[:20], ridge_celsius[:20], marker="o")

axes[1].plot(days[:20], ridge_celsius[:20], marker="^",
             markersize=10, markerfacecolor="r",
             markeredgecolor="k")

# Grid
ax.grid(which="major", linewidth=1)
ax.grid(which="minor", linestyle="--", linewidth=0.4)

# Ticks
ax.set_xticks([0, 91, 182, 274, 366])
ax.set_yticks(np.arange(-10, 21, 1), minor=True)    # minor ticks: every 1 °C

# Label with mathtext
ax.set_ylabel("discharge, $Q$ (m$^3$ s$^{-1}$)")

# Axis limits
ax.set_xlim(60, 150)     # zoom to March-May


In [ ]:
# Scatterplot
ig, axes = plt.subplots(1, 2, figsize=(10, 3.6))

# colour mapped to day of year, size mapped to distance from the annual mean -- a
# third and fourth variable shown without a third and fourth axis
deviation_celsius = np.abs(ts_celsius - ts_celsius.mean())
sc = axes[0].scatter(ts_celsius, rh_percent, c=days,
                     s=5 + 4 * deviation_celsius, cmap="viridis")
fig.colorbar(sc, ax=axes[0], label="day of year")
axes[0].set_xlabel("temperature (°C)")
axes[0].set_ylabel("relative humidity (%)")
axes[0].set_title("humidity against temperature")

axes[1].hist(ts_celsius, bins=24, color="tab:gray")
axes[1].set_xlabel("temperature (°C)")
axes[1].set_ylabel("count (days)")
axes[1].set_title("distribution of daily means")

plt.tight_layout()
plt.show()

In [ ]:
# Barplot
stations = ["valley", "ridge", "mountain"]
annual_mean_celsius = [ts_celsius.mean(), ridge_celsius.mean(), mountain_celsius.mean()]

fig, axes = plt.subplots(figsize=(10, 3.5), ncols=2)
axes[0].bar(stations, annual_mean_celsius, color="tab:orange")
axes[0].set_ylabel("annual mean temperature (°C)")

axes[1].barh(stations, annual_mean_celsius, color="tab:orange")
axes[1].set_xlabel("annual mean temperature (°C)")

plt.tight_layout()
plt.show()

In [ ]:
#pcolormesh
lon2d, lat2d = np.meshgrid(lon, lat)
print(lon2d.shape, lat2d.shape)

fig, axes = plt.subplots(ncols=2, figsize=(11, 3.6))
pc0 = axes[0].pcolormesh(lon, lat, field_celsius)          # 1D coordinates
pc1 = axes[1].pcolormesh(lon2d, lat2d, field_celsius)      # 2D coordinates: same thing
fig.colorbar(pc0, ax=axes[0], label="temperature (°C)")
fig.colorbar(pc1, ax=axes[1], label="temperature (°C)")

for ax in axes:
    ax.set_xlabel("longitude (°E)")
    ax.set_ylabel("latitude (°N)")
plt.tight_layout()
plt.show()

In [ ]:
# Contour
fig, axes = plt.subplots(figsize=(11, 3.6), ncols=2)

# same thing, 1D and 2D coordinates
axes[0].contour(lon_fine, lat_fine, pressure_hpa)
axes[1].contour(lon_f2d, lat_f2d, pressure_hpa)

for ax in axes:
    ax.set_xlabel("longitude (°E)")
    ax.set_ylabel("latitude (°N)")
plt.tight_layout()
plt.show()

In [ ]:
# Maps with cartopy
import cartopy.crs as ccrs
import cartopy.feature as cfeature

fig, ax = plt.subplots(figsize=(8, 4), subplot_kw={"projection": ccrs.PlateCarree()})
ax.add_feature(cfeature.OCEAN, facecolor="#a6cee3") # ocean polygons
ax.add_feature(cfeature.LAND, facecolor="#b2df8a")  # land polygons
ax.add_feature(cfeature.COASTLINE, linewidth=0.5)
ax.gridlines(draw_labels=True, linewidth=0.3, alpha=0.5)
ax.set_title("PlateCarree")
plt.show()
# .cfeature.BORDERS country boundaries, .cfeature.COASTLINE, .cfeature.LAKES, .cfeature.LAND

# Different projecitons
projections = [ccrs.PlateCarree(), ccrs.Robinson(), ccrs.Mercator(),
               ccrs.Orthographic(central_longitude=10, central_latitude=45)]
names = ["PlateCarree", "Robinson", "Mercator", "Orthographic"]

fig = plt.figure(figsize=(10, 6))
for i, (proj, name) in enumerate(zip(projections, names)):
    ax = fig.add_subplot(2, 2, i + 1, projection=proj)
    ax.add_feature(cfeature.OCEAN, facecolor="#a6cee3")
    ax.add_feature(cfeature.LAND, facecolor="#b2df8a")
    ax.add_feature(cfeature.COASTLINE, linewidth=0.4)
    ax.set_title(name)
plt.tight_layout()
plt.show()

# Choosing a projection
#Atmospheric = PlateCarree
#Oceanography = Spilhaus
#Geography = EqualEarth